import json
import concurrent.futures
from typing import Dict
from pathlib import Path
from langchain_core.messages import SystemMessage, HumanMessage
from src.agent.state import AgentState
from src.tools.llm import safe_llm_invoke
from src.agent.prompts import (
    SYNTHESIS_OUTLINE_SYSTEM,
    SYNTHESIS_OUTLINE_USER,
    SYNTHESIS_SECTION_SYSTEM,
    SYNTHESIS_SECTION_USER,
)

def _generate_section_worker(
    section: dict,
    outline_str: str,
    title: str,
    state: AgentState,
    subagent_findings_md: str,
    timeline_md: str,
    bias_md: str,
    intel_md: str
) -> str:
    section_id = section.get("id", 1)
    section_heading = section.get("heading", "")
    section_description = section.get("description", "")
    
    subsections_lines = []
    for sub in section.get("subsections", []):
        subsections_lines.append(f"- Subsection: {sub.get('heading', '')}\n  Guidelines: {sub.get('description', '')}")
    subsections_md = "\n".join(subsections_lines) or "No subsections specified."
    
    user_prompt = SYNTHESIS_SECTION_USER.format(
        section_id=section_id,
        section_heading=section_heading,
        section_description=section_description,
        subsections_md=subsections_md,
        topic=state["topic"],
        full_outline_md=outline_str,
        subagent_findings_md=subagent_findings_md,
        timeline_md=timeline_md,
        bias_md=bias_md,
        intel_md=intel_md
    )
    
    try:
        res = safe_llm_invoke([
            SystemMessage(content=SYNTHESIS_SECTION_SYSTEM),
            HumanMessage(content=user_prompt),
        ], temperature=0.2)
        content = res.content.strip()
        
        # Ensure first section has the title envelope if not generated by LLM
        if section.get("is_introduction", False):
            if "<title>" not in content:
                envelope = f"<title>{title}</title>\n\n# {title}\n\n"
                if content.startswith("# ") or content.startswith("#\n"):
                    lines = content.split("\n")
                    content = "\n".join(lines[1:])
                content = envelope + content
        return content
    except Exception as e:
        print(f"  [SynthesisEngine] Error generating section {section_id} ({section_heading}): {e}")
        return f"## {section_heading}\n\nFailed to generate content for this section."


def synthesis_node(state: AgentState) -> Dict:
    print(f"\n [SynthesisEngine] Compiling intelligence brief...")

    # Build structured contexts
    timeline_md = "\n".join(
        f"- **{e['date']}** — {e['event']}"
        f"{'  CONFLICT' if e['conflict_flag'] else ''}"
        f" [{e['confidence']} confidence]"
        for e in sorted(state.get("chronology", []), key=lambda x: x["date"])
    ) or "No dated events extracted."

    bias_md = "\n".join(
        f"- `{e['domain']}` → {e['lean']} | reliability: {e['reliability']}"
        f"{' |  MODEL DISAGREEMENT' if e['model_disagreement'] else ''}"
        for e in state.get("bias_matrix", [])
    ) or "No bias classifications available."

    # Read detailed subagent report files from disk (increased cap to 15000 chars)
    artifact_texts = []
    for path_str in state.get("subagent_artifacts", []):
        p = Path(path_str)
        if p.exists():
            try:
                text = p.read_text(encoding="utf-8")
                artifact_texts.append(f"### Findings from Subagent report ({p.stem}):\n{text[:15000]}\n---")
            except Exception as e:
                print(f"  [SynthesisEngine] Error reading artifact {p.name}: {e}")

    subagent_findings_md = "\n\n".join(artifact_texts) or "No subagent artifact files available."

    intel_items = state.get("raw_intel", [])[:20]
    intel_md = "\n\n".join(
        f"**[{r.get('published_date','?')}] {r.get('title','Untitled')}**\n"
        f"{r.get('snippet','')[:800]}\n"
        f"Source: {r.get('source_url','')}"
        for r in intel_items
    ) or "No intel records."

    # 1. Draft the outline
    outline_prompt = SYNTHESIS_OUTLINE_USER.format(
        topic=state["topic"],
        subagent_findings_md=subagent_findings_md,
        timeline_md=timeline_md,
        intel_md=intel_md
    )
    
    outline_data = None
    try:
        res = safe_llm_invoke([
            SystemMessage(content=SYNTHESIS_OUTLINE_SYSTEM),
            HumanMessage(content=outline_prompt)
        ], temperature=0.1)
        raw_json = res.content.strip()
        # Clean JSON wrappers
        if raw_json.startswith("```json"):
            raw_json = raw_json[7:]
        if raw_json.endswith("```"):
            raw_json = raw_json[:-3]
        outline_data = json.loads(raw_json.strip())
    except Exception as e:
        print(f"  [SynthesisEngine] Failed to generate/parse JSON outline: {e}. Using fallback outline.")
        outline_data = {
            "title": f"Strategic Analysis: {state['topic']}",
            "sections": [
                {
                    "id": 1,
                    "heading": "Introduction & Scope of Inquiry",
                    "is_introduction": True,
                    "description": "Establish the background, context, and key themes of the research.",
                    "subsections": []
                },
                {
                    "id": 2,
                    "heading": "Core Analysis & Current Landscape",
                    "is_introduction": False,
                    "description": "Analyze the main findings, raw data, and specific events.",
                    "subsections": []
                },
                {
                    "id": 3,
                    "heading": "Synthesis & Key Implications",
                    "is_introduction": False,
                    "description": "Discuss future projections, conflicts, and strategic recommendations.",
                    "subsections": []
                }
            ]
        }

    # Format outline as markdown for prompts
    outline_lines = []
    outline_lines.append(f"Title: {outline_data.get('title', state['topic'])}")
    for sec in outline_data.get("sections", []):
        intro_tag = " (Introduction)" if sec.get("is_introduction") else ""
        outline_lines.append(f"Section {sec.get('id')}: {sec.get('heading')}{intro_tag}")
        outline_lines.append(f"  Description: {sec.get('description')}")
        for sub in sec.get("subsections", []):
            outline_lines.append(f"    Subsection: {sub.get('heading')}")
    outline_str = "\n".join(outline_lines)

    sections = outline_data.get("sections", [])
    title = outline_data.get("title", f"Strategic Analysis: {state['topic']}")
    print(f"  [SynthesisEngine] Generated outline with {len(sections)} sections.")

    # 2. Generate sections in parallel
    section_texts = [None] * len(sections)
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(sections)) as executor:
        futures = {
            executor.submit(
                _generate_section_worker,
                sec,
                outline_str,
                title,
                state,
                subagent_findings_md,
                timeline_md,
                bias_md,
                intel_md
            ): i
            for i, sec in enumerate(sections)
        }
        for future in concurrent.futures.as_completed(futures):
            idx = futures[future]
            sec = sections[idx]
            try:
                content = future.result()
                section_texts[idx] = content
                print(f"  [SynthesisEngine] Section {sec.get('id')} complete.")
            except Exception as e:
                print(f"  [SynthesisEngine] Section {sec.get('id')} failed: {e}")
                section_texts[idx] = f"## {sec.get('heading')}\n\nFailed to generate content."

    # Assemble report
    assembled_synthesis = "\n\n".join(t for t in section_texts if t is not None)

    print(f"  Synthesis complete ({len(assembled_synthesis)} chars)")
    return {"synthesis": assembled_synthesis}
